### ISSUE TITLE
Readme doesn't help with building. 

### ISSUE THREAD

**Issue by Muzz** [martincohen/Punity#1]
Hey mate, thought i would give this a shot and try to build, but this really isn't setup for other people to use, which is a shame as a tiny little c engine is a pretty cool idea as a learning tool.

first off the readme is wrong, it seems to look for sdl in a base level folder called SDL2 rather than a folder called SDL in lib. 

Then there is no samples and no explanation of the asset packing. I get this is a fun little project for you but i don't see the point in a public repository unless you are going to at least have a sample and make sure the build instructions is correct. 

I hope you can fix this stuff up so others can have a play! 

-Muzz

**Comment by martincohen** [comment]
I'm sorry for any inconvenience. Current repository version of Punity is very old. I suggest you to take a look at my LudumDare game called [33 grams](http://ludumdare.com/compo/ludum-dare-34/?action=preview&uid=55211) ([source](https://dl.dropboxusercontent.com/u/5799921/LD34/33grams-v5-source.zip)). That has a more current version of Punity as well as enough of example code to let you play with it.

I have a newer version of Punity with much more advanced features in the making, but as this is really a fun little project for me, it'll take a while until it matures. Until then I cannot provide much support for people who want to use it as a whole. The main reason for it being public is for people who want to take a look at the code, maybe even adopt it for their own use.

**Comment by martincohen** [comment]
Hello good sir, I've just pushed a new and reworked version of Punity to the repo, completely replacing the old code. I hope this message will ping you somewhere. <3
