### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [martincohen/Punity#2]
I would like to point out that an identifier like "[`_SOUND_CHANNELS`](https://github.com/martincohen/Punity/blob/8f179c25e9d094bdbfa21ddcd99ce374328f32d3/punity.c#L33)" [does not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier) to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by gingerBill** [comment]
However, does this actually cause problems in practice? If it is, something like PUNITY_SOUND_CHANNELS_ may be better or something else.

**Comment by martincohen** [comment]
Thanks for the report! Fix is done, I used "PUNP" to prefix punity's private identifiers. There were more people complaining about it and I rather stay out of violations with a public project. Suffix underscore seem to be ok?

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/martincohen/Punity/commit/82b3da2b12157997b3ba4afc205345158d6e081f#diff-639554536c5a830da9fc6a31625bf25cL29).
