### ISSUE TITLE
Audio issue

### ISSUE THREAD

**Issue by leonu2** [martincohen/Punity#3]
When running just the default files and code from your github I noticed that every time I pressed the spacebar to use the sound2.ogg it would leave a little bit of a clicking sound in the background and every time space is pressed it increases a bit in volume. I tried a different .ogg at rates of 16000 and 48000 and there doesn't seem to be any clicking. Not too sure if this is an issue of the way sound is loaded or just the sound2.ogg file itself but thought I'd mention it in case sounds similar to the .ogg have the same issue.

**Comment by martincohen** [comment]
Hello! Thanks for the report!

Have you tried to play the res/sound2.ogg file in something else for comparision? (Probably also comment the line sound2.rate = 48000; in main.c to hear it in the original version via Punity). I'll investigate nonetheless. <3

**Comment by martincohen** [comment]
I think there's a clicking sound when you hit space before the sound finishes (so it has to mix two instances of the sound). So it might be problem in the mixer...

**Comment by martincohen** [comment]
Yep, confirmed, the mixing is clipping. I'll take a look at what can be done. Until then I suggest you to use sounds at half volume (master and per-sound volume control is on the way).

**Comment by leonu2** [comment]
Awesome! Yeah it's not a huge issue when I changed the rates or volume. I couldn't really tell why it was happening, still pretty new to C, but glad you seem to know!
