### ISSUE TITLE
Bitmap loading error?

### ISSUE THREAD

**Issue by estebangames842** [martincohen/Punity#9]
Hello, i was testing a bit your engine, and it seems that im not able to load a bitmap and draw it on the screen, i got this error message: 
![error](https://user-images.githubusercontent.com/36859022/36742913-b3dc818a-1bc7-11e8-91e4-4fbcce39f218.png)
here is my code: 
``#define PUNITY_IMPLEMENTATION
#include "punity.h"
Bitmap image;
typedef struct Game_
{
    Bitmap font;
}
Game;

static Game *GAME = 0;

int
init()
{
    GAME = bank_push_t(CORE->storage, Game, 1);

    font_load_resource(&GAME->font, "font.png", 4, 7);
    CORE->canvas.font = &GAME->font;
	Bitmap* imagee = &image;
	bitmap_load_resource(imagee, "image.png", 0);
    return 1;
}

void
step()
{
    canvas_clear(1);
	Bitmap* imagee = &image;
	Rect oho = rect_make(60, 100, 40, 140);
	Rect* oo = &oho;
	bitmap_draw(imagee, 60, 10, 0, 0, oo);
    if (key_down(KEY_ESCAPE)) {
        CORE->running = 0;
    }
    

}

I tried changing Assert(comp == 4) to Assert(comp = 4), this seems to work, but it fills the rest of the screen with the main colour of the image.

i just dont know what's happening
PS: i do have image.png declared in the main.rc

**Comment by martincohen** [comment]
What format is the `image.png`, please? (32-bit, 24-bit, 8-bit?)

**Comment by martincohen** [comment]
No response, closing.
